spring.application.name=tp-backend
server.port=8080
management.endpoints.web.exposure.include=health,info
springdoc.swagger-ui.path=/api/swagger-ui/index.html
springdoc.api-docs.path=/api/v3/api-docs

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gestion}
spring.datasource.username=${DB_USER:gestion_user}
spring.datasource.password=${DB_PASSWORD:gestion_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update