spring.application.name=tp-backend
server.port=8080
management.endpoints.web.exposure.include=health,info
springdoc.swagger-ui.path=/api/swagger-ui/index.html
springdoc.api-docs.path=/api/v3/api-docs
